import { Database, ListFilter, MapPinned, Navigation, RotateCw, Wind } from 'lucide-react';
import { useMemo } from 'react';
import type { AqiDataset, AqiStationRecord } from '../lib/aqi';
import { formatHours, formatNumber } from '../lib/format';
import { getTaiwanMapPoint, sortStationsForMap } from '../lib/mapLayout';
import { STATION_SELECTION_GUIDANCE } from '../lib/stationSelection';
import { StatusBadge } from './StatusBadge';

type TaiwanAirMapProps = { dataset: AqiDataset; selectedCounty: string; selectedStation: AqiStationRecord | null; onCountyChange: (county: string) => void; onStationSelect: (station: AqiStationRecord) => void; onRefresh: () => void; isRefreshing: boolean };
const pollutants: Array<[keyof AqiStationRecord['pollutantValues'], string, string]> = [['pm25', 'PM2.5', 'μg/m³'], ['pm10', 'PM10', 'μg/m³'], ['o3', 'O₃', 'ppb'], ['co', 'CO', 'ppm']];

export function TaiwanAirMap({ dataset, selectedCounty, selectedStation, onCountyChange, onStationSelect, onRefresh, isRefreshing }: TaiwanAirMapProps) {
  const { records, summary } = dataset;
  const official = dataset.source.kind === 'official-cache';
  const current = useMemo(() => official ? records.filter((station) => !station.isStale) : [], [official, records]);
  const counties = useMemo(() => ['all', ...new Set(records.map((station) => station.county).sort((a, b) => a.localeCompare(b, 'zh-Hant')))], [records]);
  const countyStations = useMemo(() => selectedCounty === 'all' ? [] : records.filter((station) => station.county === selectedCounty).sort((a, b) => a.stationName.localeCompare(b.stationName, 'zh-Hant')), [records, selectedCounty]);
  const visible = useMemo(() => {
    const candidates = current.length ? current : records;
    if (selectedCounty !== 'all') return sortStationsForMap(candidates.filter((station) => station.county === selectedCounty));
    const representative = new Map<string, AqiStationRecord>();
    candidates.forEach((station) => { const saved = representative.get(station.county); if (!saved || station.aqi > saved.aqi) representative.set(station.county, station); });
    return sortStationsForMap([...representative.values()].sort((a, b) => b.aqi - a.aqi).slice(0, 12));
  }, [current, records, selectedCounty]);
  const canAdvise = Boolean(selectedStation && official && !selectedStation.isStale);
  const sourceLabel = official ? '官方快取' : dataset.source.kind === 'sample' ? '範例資料' : '備援資料';
  const freshness = !official ? '非即時資料 · 不提供現在結論' : summary.isStale ? '資料已超過時效 · 現在結論已暫停' : `資料新鮮 · ${formatHours(summary.hoursSinceUpdate)}`;

  return <section aria-labelledby="aqi-heading" className="overflow-hidden rounded-[20px] border border-[#c9d7d1] bg-white/75 shadow-dashboard">
    <div className="border-b border-[#dce6e1] bg-[linear-gradient(110deg,rgba(15,118,110,.11),rgba(34,211,238,.09),rgba(255,255,255,.55))] px-5 py-5 sm:px-7">
      <div className="flex flex-wrap items-center justify-between gap-3"><span className="inline-flex items-center gap-2 rounded-full border border-[#9ac9c2] bg-white/70 px-3 py-1.5 text-xs font-bold text-[#0f625c]"><Wind aria-hidden="true" className="h-4 w-4" />所在地空氣快查</span><span className={`rounded-full border px-3 py-1.5 text-xs font-bold ${official && !summary.isStale ? 'border-[#9ac9c2] bg-[#e6f5f1] text-[#0f625c]' : 'border-amber-300 bg-amber-50 text-amber-900'}`}>{sourceLabel} · {freshness}</span></div>
      <h1 id="aqi-heading" className="mt-5 max-w-3xl text-3xl font-black tracking-tight text-[#10211c] sm:text-4xl">先確認你所在地的空氣品質</h1>
      <p className="mt-2 max-w-2xl text-sm leading-6 text-[#426058]">選擇縣市與測站，立即查看 AQI、主要污染物、發布時間和資料是否足以用於現在的活動判斷。</p>
    </div>
    <div className="grid gap-5 p-5 lg:grid-cols-[minmax(260px,.75fr)_minmax(340px,1.12fr)_minmax(300px,.9fr)] lg:p-6">
      <div className="space-y-4"><div className="rounded-2xl border border-[#c9d7d1] bg-[#f8fbf9] p-4"><p className="text-xs font-black tracking-[.12em] text-[#52706a]">選擇所在地</p>
        <label className="mt-4 block"><span className="mb-2 flex items-center gap-2 text-sm font-bold text-[#24473e]"><ListFilter aria-hidden="true" className="h-4 w-4 text-[#0f766e]" />1. 縣市</span><select name="primary-county" value={selectedCounty} onChange={(event) => onCountyChange(event.target.value)} className="h-11 w-full rounded-xl border border-[#b8cbc4] bg-white px-3 text-sm font-semibold text-[#10211c]">{counties.map((county) => <option key={county} value={county}>{county === 'all' ? '請選擇縣市' : county}</option>)}</select></label>
        <label className="mt-4 block"><span className="mb-2 flex items-center gap-2 text-sm font-bold text-[#24473e]"><MapPinned aria-hidden="true" className="h-4 w-4 text-[#0f766e]" />2. 測站</span><select name="primary-station" value={selectedStation?.siteId ?? ''} onChange={(event) => { const station = countyStations.find((item) => item.siteId === event.target.value); if (station) onStationSelect(station); }} disabled={selectedCounty === 'all' || countyStations.length === 0} className="h-11 w-full rounded-xl border border-[#b8cbc4] bg-white px-3 text-sm font-semibold text-[#10211c] disabled:cursor-not-allowed disabled:bg-[#edf1ef] disabled:text-[#6b7d76]"><option value="">{selectedCounty === 'all' ? '請先選縣市' : countyStations.length ? '請選擇測站' : '此縣市沒有測站'}</option>{countyStations.map((station) => <option key={station.siteId} value={station.siteId}>{station.stationName}{station.isStale ? '（資料過期）' : ''}</option>)}</select></label>
        <button type="button" onClick={onRefresh} disabled={isRefreshing} className="mt-4 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#0f766e] px-4 text-sm font-bold text-white transition hover:bg-[#0b625b] disabled:cursor-wait disabled:bg-[#79a9a2]"><RotateCw aria-hidden="true" className={`h-4 w-4 ${isRefreshing ? 'animate-spin motion-reduce:animate-none' : ''}`} />{isRefreshing ? '正在更新…' : '重新讀取快取'}</button></div>
        <p className="rounded-xl border border-[#d7e2de] bg-white p-3 text-xs leading-5 text-[#52706a]"><strong className="text-[#24473e]">選站提醒：</strong>{STATION_SELECTION_GUIDANCE.text} <a className="font-bold text-[#0f766e] underline underline-offset-2" href={STATION_SELECTION_GUIDANCE.sourceUrl} target="_blank" rel="noreferrer">了解測站類型</a></p></div>
      <div className="air-map-grid relative min-h-[390px] overflow-hidden rounded-2xl border border-[#c9d7d1] bg-[#f4faf8]" aria-label="台灣測站示意分布"><span className="absolute left-4 top-4 z-10 rounded-full border border-[#c9d7d1] bg-white/90 px-3 py-1.5 text-xs font-bold text-[#36544c]">{selectedCounty === 'all' ? '全台代表測站' : `${selectedCounty} 測站`} · {visible.length} 站 · 示意分布</span>
        <svg className="absolute left-1/2 top-1/2 h-[86%] w-[68%] -translate-x-1/2 -translate-y-1/2" viewBox="0 0 380 620" role="img" aria-label="台灣輪廓示意，非精密地圖"><path d="M226 26C272 62 284 123 272 177C262 222 298 255 283 307C267 362 225 393 213 451C203 501 171 566 134 593C121 602 105 590 111 574C125 537 107 493 103 455C96 394 134 355 116 293C99 233 94 176 130 124C154 89 173 43 206 26C212 23 219 22 226 26Z" fill="rgba(15,118,110,.13)" stroke="rgba(15,118,110,.48)" strokeWidth="5" /><path d="M203 58C226 100 215 154 232 198C252 251 235 294 220 342C205 392 184 432 174 481C167 514 151 550 130 575" fill="none" stroke="rgba(15,118,110,.24)" strokeDasharray="10 14" strokeWidth="3" /></svg>
        {visible.map((station) => { const point = getTaiwanMapPoint(station); if (!point) return null; const picked = station.siteId === selectedStation?.siteId; return <button key={station.siteId} type="button" aria-label={`查看 ${station.county}${station.stationName}，AQI ${station.aqi}`} onClick={() => onStationSelect(station)} className={`air-map-marker group absolute z-[2] grid h-10 w-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 bg-white text-[10px] font-black text-[#10211c] shadow-soft transition hover:scale-110 ${picked ? 'ring-4 ring-[#0f766e]/25' : ''} ${!official || station.isStale ? 'opacity-55 grayscale' : ''}`} style={{ left: `${point.x}%`, top: `${point.y}%`, borderColor: station.category.color }}><span>{station.aqi}</span><span className="pointer-events-none absolute top-full mt-2 hidden min-w-max rounded-lg bg-[#10211c] px-2 py-1 text-xs font-semibold text-white group-hover:block group-focus:block">{station.county} {station.stationName}</span></button>; })}
        <div className="absolute bottom-3 left-3 right-3 flex flex-wrap gap-x-3 gap-y-1 rounded-xl border border-[#d7e2de] bg-white/90 px-3 py-2 text-[10px] font-semibold text-[#52706a]"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#16803c]" />良好</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#b77900]" />普通</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#c45a16]" />敏感族群不健康</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#c52222]" />不健康以上</span></div></div>
      <aside className="rounded-2xl border border-[#c9d7d1] bg-white p-5" aria-live="polite">{selectedStation ? <StationDetail station={selectedStation} canAdvise={canAdvise} official={official} /> : <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><Database aria-hidden="true" className="h-9 w-9 text-[#0f766e]" /><h2 className="mt-4 text-lg font-black text-[#10211c]">選擇所在地測站</h2><p className="mt-2 max-w-xs text-sm leading-6 text-[#52706a]">{records.length === 0 ? '目前沒有可顯示的測站。' : selectedCounty === 'all' ? '先選擇縣市，再選擇測站。本站不要求定位權限。' : `已選擇 ${selectedCounty}，請選擇一個測站。`}</p></div>}</aside>
    </div></section>;
}

function StationDetail({ station, canAdvise, official }: { station: AqiStationRecord; canAdvise: boolean; official: boolean }) { return <div><div className="flex items-start justify-between gap-3"><div><p className="inline-flex items-center gap-1 text-xs font-bold text-[#52706a]"><MapPinned aria-hidden="true" className="h-3.5 w-3.5" />{station.county} · 所在地測站</p><h2 className="mt-2 text-2xl font-black text-[#10211c]">{station.stationName}</h2><p className="mt-1 text-xs text-[#52706a]">發布：{station.publishTime || '未知'} · {station.hasFutureTimestamp ? '時間戳異常' : formatHours(station.hoursSinceUpdate)}</p></div><div className="grid h-20 w-20 shrink-0 place-items-center rounded-2xl border-4 bg-[#f8fbf9]" style={{ borderColor: station.category.color }}><div className="text-center"><span className="block text-[10px] font-bold text-[#52706a]">{canAdvise ? 'AQI' : '快取 AQI'}</span><span className="text-3xl font-black tabular-nums text-[#10211c]">{station.aqi}</span></div></div></div><div className="mt-4">{canAdvise ? <StatusBadge category={station.category} /> : <span className="inline-flex rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-sm font-bold text-amber-900">{official ? '資料過期 · 不代表現在狀況' : '展示資料 · 不代表現在狀況'}</span>}</div><div className={`mt-4 rounded-xl border p-4 ${canAdvise ? 'border-[#b9d9d2] bg-[#eff9f6]' : 'border-amber-200 bg-amber-50'}`}><p className="flex items-center gap-2 text-sm font-black text-[#24473e]"><Navigation aria-hidden="true" className="h-4 w-4" />{canAdvise ? '目前活動提醒' : '現在建議已暫停'}</p><p className="mt-2 text-base font-bold text-[#10211c]">{canAdvise ? station.category.advice.short : '此筆資料僅保留查核，不作現在判斷。'}</p>{canAdvise && <><p className="mt-3 text-xs font-bold text-[#52706a]">一般民眾</p><p className="mt-1 text-sm leading-6 text-[#36544c]">{station.category.advice.general}</p><p className="mt-3 text-xs font-bold text-[#52706a]">敏感族群</p><p className="mt-1 text-sm leading-6 text-[#36544c]">{station.category.advice.sensitive}</p></>}</div><dl className="mt-4 grid grid-cols-2 gap-2" aria-label={canAdvise ? '目前污染物數值' : '快取污染物數值'}>{pollutants.map(([key, label, unit]) => <div key={key} className="rounded-xl bg-[#f3f7f5] p-3"><dt className="text-xs font-bold text-[#52706a]">{label}</dt><dd className="mt-1 font-black tabular-nums text-[#10211c]">{formatNumber(station.pollutantValues[key], key === 'co' ? 2 : 0)} <small className="font-medium text-[#52706a]">{unit}</small></dd></div>)}</dl></div>; }
